# API
FROM node:16-alpine3.18

ENV NODE_ENV=development
ENV EXT_PORT=4000
ENV INT_PORT=5000

RUN apk update
RUN apk add vim

WORKDIR /app

EXPOSE ${EXT_PORT} ${INT_PORT} 

CMD [ "npm", "run", "develop_start" ]


# Auth

FROM node:16-alpine3.18

ENV NODE_ENV=development
ENV CONTENTSPORT=8443
ENV APIPORT=443

RUN apk update
RUN apk add vim

WORKDIR /app


EXPOSE ${CONTENTSPORT} ${APIPORT}
CMD [ "npm", "run", "develop_start" ]